export const CREATE_STUDENT_REQUEST = "CREATE_STUDENT_REQUEST";
export const CREATE_STUDENT_SUCCESS = "CREATE_STUDENT_SUCCESS";
export const CREATE_STUDENT_FAIL = "CREATE_STUDENT_FAIL";
export const CREATE_STUDENT_RESET = "CREATE_STUDENT_RESET";

export const GET_STUDENT_REQUEST = "GET_STUDENT_REQUEST";
export const GET_STUDENT_SUCCESS = "GET_STUDENT_SUCCESS";
export const GET_STUDENT_FAIL = "GET_STUDENT_FAIL";

export const UPDATE_STUDENT_REQUEST = "UPDATE_STUDENT_REQUEST";
export const UPDATE_STUDENT_SUCCESS = "UPDATE_STUDENT_SUCCESS";
export const UPDATE_STUDENT_RESET = "UPDATE_STUDENT_RESET";
export const UPDATE_STUDENT_FAIL = "UPDATE_STUDENT_FAIL";

export const ALL_STUDENTS_REQUEST = "ALL_STUDENTS_REQUEST";
export const ALL_STUDENTS_SUCCESS = "ALL_STUDENTS_SUCCESS";
export const ALL_STUDENTS_FAIL = "ALL_STUDENTS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS"; 